function read_file(fname)
	local fh = io.open(fname, 'r')
	local text = fh:read('*a')
	fh:close()
	return text
end

function file_name_variant(base, variant)
	local basename, suffix, ret
	basename, suffix = string.match(base, '^(.+)%.(.*)$')
	return basename .. '-' .. variant .. '.' .. suffix
end

function read_file_variant(fname, variant)
	local fh, text
	if variant then
		fh = io.open(file_name_variant(fname, variant), 'r') or io.open(fname, 'r')
	end
	if not fh then
		fh = io.open(fname, 'r')
	end
	text = fh:read('*a')
	fh:close()
	return text
end

function resize_w(px, zoom)
	return string.format('%0.3f', px * math.pow(1.5, 12-zoom) )
end

local header = [[
<?xml version="1.0" encoding="UTF-8"?>
<rendertheme xmlns="http://mapsforge.org/renderTheme" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://mapsforge.org/renderTheme ../renderTheme.xsd" version="1" map-background="#F8F8F8">
<!-- autogenerated via preprocess.lua -->
]]

local footer = [[
</rendertheme>
]]

local variant = arg[1] or nil

local template = read_file_variant('body.txt', variant)


local vsuffix = ''
if variant then
	vsuffix = '-' .. variant
end

local outp = io.open('metropolis' .. vsuffix .. '.xml', 'w+')
outp:write(header)
outp:write(read_file_variant('info.txt', variant))

local max_zoom = 17

for zoom=12,max_zoom do
	local tmp = template
	
	tmp = string.gsub(tmp, 'width="(%d+)"', function(px) return 'width="' .. resize_w(px, zoom)..'"'  end)
	
	outp:write('<rule e="any" k="*" v="*" ')
	if zoom>12 then
		outp:write('zoom-min="'..zoom..'" ' )
	end
	if zoom<max_zoom then
		outp:write('zoom-max="'..zoom..'" ' )
	end
	outp:write('>\n')
	
	
	outp:write(tmp .. '\n')
	outp:write('</rule>\n\n')
end

outp:write(read_file_variant('tail.txt', variant))
outp:write(footer)
outp:close()